server:
  port: ${SERVER_PORT:9011}

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 123456
    jpa:
      open-in-view: false
      show-sql: true
      hibernate:
        format_sql: true
        ddl-auto: validate
    initialization-mode: always
